### ISSUE TITLE
[Bug] Невидимые иконки подствольного гранатомета и фонарика

### ISSUE THREAD

**Issue by MoXuT0** [FighterX2500/DMCAMarines#14]
![default](https://user-images.githubusercontent.com/34478337/44543889-8019de00-a719-11e8-9cb5-2a3458ef2b4b.png)
Скорее всего связана с добавлением кнопки для отдачи приказов.

**Comment by carrotman2013** [comment]
Закрой и больше никогда не открывай

**Comment by carrotman2013** [comment]
я не шучу все очень серьезно, дело очень тонкое, а фикс уже в пулл-реквестах.
