### ISSUE TITLE
[Suggest] Оаоаоаоа)))оаоа

### ISSUE THREAD

**Issue by KriegDebik** [FighterX2500/DMCAMarines#184]
Моя идея довольно простая:
-Дать всему маринаду доступ юзать вендоры MarineMed.
-Объединить комнаты отрядов Дельты с Чарли, Альфу с Браво.
-Сделать уже починенные генераторы, остается лишь следить за их зарядом.
-Дать спиттеру абилку для спрея кислотой. А то он является помойкой, которые может лишь получше плавить айтемы и аирлоки, и хорошо станить кислотой за 50 плазмы.
Даб-даб-даб я.

**Comment by MrShepard** [comment]
Ща сделаем.

**Comment by carrotman2013** [comment]
тут уже все впилено
