### ISSUE TITLE
[Suggest] Мини отряды

### ISSUE THREAD

**Issue by Avatar4** [FighterX2500/DMCAMarines#232]
Сделать возможность создавать мини отряды в одном глобальном.
Как пример, парочка друзей в сске создают мини отряд в отряде альфы с собственным названием и сами выбирают кто из них будет медиком илитде инженером, морпехом. Они все ещё будут подчиняться приказам лидера отряда и прочим, но будет гарантом того что они будут действовать в здоровой кооперации группы между собой. В команду можно было бы сделать ограничения с трёх до восьми товарищей что бы не было миллион отрядов по одному человеку.

Никаких дополнительных плюшек им выдавать не надо дабы не было смысла абуза. Хотел быть снайпером в отряде но не повезло и роль забрали? Что ж, будь обычным морпехом.
Ты понял правило о отряде не правильно и уже кричишь кооп дружкам в скайпе что тебя утаскивают на другом конце карты без внутриигровой инфы? Вероятно тебе доступ к этим мини отрядам не нужен.

Данная функция как по мне, дает возможность почувствовать себя настоящим спецназом с проверенными соратниками на которых ты можешь положиться.

**Comment by cofecofe3** [comment]
Ahem... Чем FT (файртимы) не устраивают?
