### ISSUE TITLE
[BUG]1.За аленя не видно труб||2.Венты перестают работать

### ISSUE THREAD

**Issue by GhostGamerr** [FighterX2500/DMCAMarines#234]
1.Я заметил что под некоторыми(!!!) поверхностями вентиляционных труб не видно - например, под ксенослизью и песке на Биг Реде. Возможно, это не единственные такие поверхности, нужно посмотреть.
2.На двух картах минимум(Биг Ред и Присонка) вентиляции иногда ломаются - просто перестают отвечать на попытки залезть в них, выводя сообщение this vent isn't connected to anything(или что-то в этом роде(вентиляции, собственно, целые, как и трубы)). От кого-то я услышал что это случается из-за повреждения системы труб - взрывом, к примеру. Это очень выбешивает, когда играешь за аленя.

**Comment by GhostGamerr** [comment]
Кстати, первую проблему репортил ещё Мохито в восемнадцатом году

**Comment by cofecofe3** [comment]
Не видно труб - это как? Есть скриншот? Это как сейчас на англах они "показываются по ходу перемещения" или вообще не отрисовываются?

**Comment by GhostGamerr** [comment]
Понял принцип того, как именно ломается система вентиляций. Думаю, это поможет с определением и починкой бага
![truba1](https://user-images.githubusercontent.com/53085902/77516873-cc904700-6e83-11ea-9281-e3180e9931d4.png)
![truba2](https://user-images.githubusercontent.com/53085902/77516879-cf8b3780-6e83-11ea-8092-49b851069b90.png)
![truba3](https://user-images.githubusercontent.com/53085902/77516884-d0bc6480-6e83-11ea-81f3-cb860a79a7c9.png)
![truba4](https://user-images.githubusercontent.com/53085902/77516887-d2862800-6e83-11ea-8583-b5412eb15cf6.png)
![truba5](https://user-images.githubusercontent.com/53085902/77516888-d44feb80-6e83-11ea-88d9-297132c825d5.png)

**Comment by Fray2** [comment]
Залито решение проблемы, на запуске если все будет нормально закрываем иссуй @GhostGamerr
