### ISSUE TITLE
[SUGGEST] Стрельба по ботоаленям

### ISSUE THREAD

**Issue by GhostGamerr** [FighterX2500/DMCAMarines#237]
Раз уж на румаринах начали повсеместно их использовать, почему бы не добавить немного деталей?
Сейчас если ты стреляешь по ботоаленю и попадаешь - нет ни звука попадания, ни измения спрайта, только звук смерти. Нужно банально добавить их - звук и покраснение спрайта(как при попадании по обычным аленям)

**Comment by VoiceInYourHead** [comment]
Я уже предложил подобную идею Тзинчу, он сказал что сделает, Гост.

**Comment by GhostGamerr** [comment]
Understood. Закрываю.
