### ISSUE TITLE
Бак X топлива для огнемета из набора маринов не подходит к огнемету

### ISSUE THREAD

**Issue by Lizurt** [FighterX2500/DMCAMarines#349]
В наборе маринов есть голубой бак с Х топливом, но его нельзя вставить в огнемет

**Comment by Fray2** [comment]
В игре есть несколько типов огнеметов - СЛовский и Пиротехника. Первый огнемет может вмещать в себя только обычные баки с топливом, а голубой Х добавили в кит по ошибке.
