### ISSUE TITLE
Магазинов Л42/патронов калибра 10-28 нет нигде, кроме набора снайпера

### ISSUE THREAD

**Issue by Lizurt** [FighterX2500/DMCAMarines#360]
В наборе снайпера есть Л42А винтовка, использующая патроны калибра 10х28. В карго нет патронов с таким калибром, и тем более магазинов

Не уверен что это баг, может так и задумывали... Но в таком случае расценивайте ишью как предложение добавить патроны такого калибра в карго

**Comment by VoiceInYourHead** [comment]
Конечно, можно добавить магазины и в карго - но на вряд ли наши великие девежоперы одобрят подобное. Ключевым образом потому, что это ИФФ-винтовка, с зажигательными и АПшными патронами, которые, в правильных руках, могут не хило так поднасрать ксенам. Так что, можно считать, что это фича.

**Comment by Lizurt** [comment]
Скорее всего пофикшено в #363
