### ISSUE TITLE
Ребаланс мортиры.

### ISSUE THREAD

**Issue by Dedlain** [FighterX2500/DMCAMarines#43]
-Увеличить точность стрельбы, чтобы разброс был от 30-40 тайлов. (Мортира слишко косая. Был явный пример вчерашний запуск на WO.)
-Увеличить урон от HE. (Из-за быстрого эволва ксен)

**Comment by Mo3goed** [comment]
А что не так с уроном то?

**Comment by RandomColonist** [comment]
Информативно пиздец. Пояснил бы в чём проблема и нахуй баффать урон, который и так неплохо дамажит и кнокает аленей и хуманов.

**Comment by FighterX2500** [comment]
Урон и так нормальный, вот точность да. Даже на оригинальных повысили её.

**Comment by JeserTheFox** [comment]
Согласен насчет повышения только точности.

**Comment by FighterX2500** [comment]
Точность увеличил в 3 раза.
