### ISSUE TITLE
SUGG: RPG and B18

### ISSUE THREAD

**Issue by Coureere** [FighterX2500/DMCAMarines#44]
B18: 

* Не защищает/плохо защищает от плевков нейротоксинам, что приводит к станлоку (который у маринов отобрали с ребалансом взрывов). Нужна стопроцентная защита от любого плевка нейротоксином и хорошая защита от кислотных плевков.

* Украсть спрайт нового шлема у мариков и БАФФНУТЬ ЗАЩИТУ ОТ ФЕЙСХАГГИНГА. Какой-нибудь кэрриер за два клика может мгновенно вывести Б18 из игры, что не есть хорошо.

RPG: 

* Нужно переосмыслить бэкбласт. Основная проблема бэкбласта в том, что где-то в 50% случаев (зависит от разных факторов, нужен тестинг на локалке) бэкбласт или какой-то иной взрыв задевает стрелка по какой-то причине (стояние возле стены, стояние в 3-4 тайлов от врага), даже если цель была поражена за 4 тайла и больше.

* В то же время, HE ракеты годятся ТОЛЬКО для мусора вроде Т1-молодых Т2, а бронебойная ракета МАКСИМУМ способна на короткий срок кнокнуть Т3, да и то не всех (крашеру и квине вообще похуй на любую ракету). Жирная проблема - крашер в режиме бега, для которого ему нужен всего один тайл разбега (один, Карл), не может быть остановлен литерали ничем кроме твёрдой преграды (танк will do). Это значит, что любая ракета в лоб даже не остановит его, не отбросит, не говоря уже про кнок или стан. Ракета, которая должна делать дырки в танках и фарш из их экипажей. Не может пробить одного аленя с толстым лбом или хотя бы затормозить его взрывом.

* Добавить фичу посторонней перезарядки и орудийного расчёта. Суть в том, что специалист может отдать часть ракет своему дружбану, который может кликнуть по нему ракетой, и при условии, что они оба стоят на соседних тайлах, у специалиста в руках незаряженный гранатомёт и они стоят на месте определённое кол-во времени (будет логично, если это будет быстрее, чем самостоятельная перезарядка, т.к. кооперация требует вознаграждения и смысла). Это позволит RPG специалисту даже при говёном уроне действовать более оперативно, быть более самостоятельной (вместе с напарником) боевой единицей и нести больше припасов в целом. Ещё добавлю, что если будет спрайт, то можно запилить специальный рюкзак на 6-7 слотов, который будет вмещать только ракеты, но в который можно будет залезть со спины АКА сумка с гранатами для советского гранатомёта.

**Comment by RandomColonist** [comment]
Алсо, чтоб не срать другими иссуями, допишу саджестшен про RPG:
Добавить фичу посторонней перезарядки и орудийного расчёта. Суть в том, что специалист может отдать часть ракет своему дружбану, который может кликнуть по нему ракетой, и при условии, что они оба стоят на соседних тайлах, у специалиста в руках незаряженный гранатомёт и они стоят на месте определённое кол-во времени (будет логично, если это будет быстрее, чем самостоятельная перезарядка, т.к. кооперация требует вознаграждения и смысла). Это позволит RPG специалисту даже при говёном уроне действовать более оперативно, быть более самостоятельной (вместе с напарником) боевой единицей и нести больше припасов в целом. Ещё добавлю, что если будет спрайт, то можно запилить специальный рюкзак на 6-7 слотов, который будет вмещать только ракеты, но в который можно будет залезть со спины АКА сумка с гранатами для советского гранатомёта.
