### ISSUE TITLE
[Suggest] Изменения танка

### ISSUE THREAD

**Issue by JeserTheFox** [FighterX2500/DMCAMarines#45]
1. Список вещей, которые надо сделать переезжаемыми:
- Fuel/water tanks
- Beer kegs
- Роллер беды и стретчеры с марином.
- Все ящиков, Ore Crates, все виды бочек и ящиков в ангаре.
- Все виды вендоров, компьютеров, автолаты, кроме уникальных вроде консолей вызова кораблей, консолей и вендоров танка, ДСов, Река.
- Двери.
- Showcases.
- Рамки СО СТЕКЛАМИ, потому что сейчас можно переехать только рамки без стекла. 
- Hydroponic trays.

2. Поставить вместо ПНВ на Арте МЕЗОНКИ.
3. Добавить стрельбу с куполы по лежачим. ТОЛЬКО с куполы.

**Comment by carrotman2013** [comment]
пункт первый давно выполнен, 2-3 прикольно
