### ISSUE TITLE
[Suggest] Изменение доступа к вендорам Req

### ISSUE THREAD

**Issue by JeserTheFox** [FighterX2500/DMCAMarines#50]
По неизвестной причине только аттачмент вендор требует повышенный доступ, в то время как вендоры в южной комнатке могут облутать даже приваты, чем многие и пользуются. 

Добавить этим двум вендорам те же требования доступа, что и у аттачмент вендора, чтобы всякие манчкины-SO-TC-PO не заходили и не брали вещи без разрешения, тем самым зля Req-персонал.

**Comment by RandomColonist** [comment]
Тут нужно огородить карго в целом, а не вендоры конкретно. Представь ситуацию - красный код, алени бегут, а ты даже гранаты из вендора взять не можешь потому что ПАШОЛ НАХУЙ ДЕД ДАЙ ДОСТУП))0. Просто обрезать SO, TC, PO доступ в карго. Хотят лут - пусть персонально просят у RO или стоят в линии, хули. Так сразу двух зайцев убьём - проблему с лутателями RO, когда всякие трапы-пилоты пиздят гранаты и АП патроны, и проблему заниженного респекта RO.

**Comment by StarRuCat** [comment]
@JeserTheFox , исправлено.

**Comment by FighterX2500** [comment]
https://github.com/FighterX2500/DMCAMarines/pull/60
Решено
