### ISSUE TITLE
[Suggest] Изменения ролек на WO

### ISSUE THREAD

**Issue by JeserTheFox** [FighterX2500/DMCAMarines#51]
https://cdn.discordapp.com/attachments/150315577943130112/478093489947672587/image.png
Адаптированный немного измененный перевод:
XO все еще XO.
CMP - Глава Почетного Караула (Honor Guard Head)
SO - Ветеран Почетного Караула (Honor Guard Vet)
TC - Специалист Почетного Караула (Honor Guard SPC)
MP - Почетный Караул (Honor Guard)
PO - Команда миномета (Mortar Crew)
RO - Квартермейстер (QuarterMaster)
CE - Глава персонала форпоста (Outpost Crew Head)
MT/CT - Персонал форпоста (Outpost Crew)
CL - военный репортер (War Reporter) just4lulz.

И добавить им соответствующие звания, конечно же.

**Comment by carrotman2013** [comment]
даааа еще бы вдобавок ебануть парочку-десяточку режимов которые никто никогда не запустит во заебись заживем тогда вообще!!!!
