### ISSUE TITLE
[Suggest] Добавить мини-Req на WO

### ISSUE THREAD

**Issue by JeserTheFox** [FighterX2500/DMCAMarines#52]
Добавить небольшой Req, в котором будет 2-3 мариковских вендора с оружем, посадить туда RO, который будет зваться QM. Добавить пару полок со вкусняшками в небольшом кол-ве, добавить 1 Рек вендор, который в Реке слева стоит, в нем должно быть много поучей, чтобы желающие могли себе набрать. После начала жести, QM будет отвечать за доставку ящичков на фронт.

**Comment by RandomColonist** [comment]
Проще просто прописать поучи в стартовые комплекты. Про персонализацию можно не пиздеть, так как ты и так оружие не выбираешь, по сути.
