### ISSUE TITLE
[Suggest] При взятии любого оружия в две руки, вещь\граб во второй руке дропается

### ISSUE THREAD

**Issue by JeserTheFox** [FighterX2500/DMCAMarines#54]
При активации/кликанья по оружию в активной руке, любая вещь\граб во второй руке автоматически дропается и оружие берется в обе руки наизготовку.

**Comment by RandomColonist** [comment]
Пулл есть на ТГмаринах.

**Comment by FighterX2500** [comment]
Скопипиздил
