### ISSUE TITLE
cas laser lock on

### ISSUE THREAD

**Issue by Leviathan21** [FighterX2500/DMCAMarines#55]
1. Лазер при наведении на ксеноса/танк/иную ходячую остается работать пока цель находиться в поле зрения наводчика. 
2.  Апдейт даст нормальное применение касу вообще, а не только как способ шугать ксеносов петардами, также даст юз миниракетам и бронебойным, что требуют нормального директ хита.

**Comment by Murenaa** [comment]
Если убрать отображение лазера для ксены, то КАСы действительно станут более играбельными, а ПО на них не будет плакать в обнимку с топ оружием, а постоянно быть в полете и кемпить важные точки

**Comment by JeserTheFox** [comment]
Не уверен насчет идеи с захватом цели, но вот полностью убирать лазер нельзя. Его просто нужно уменьшить, чтобы он был маленьким, но все-таки заметным ИЛИ сделать захват цели, что-то одно.

**Comment by carrotman2013** [comment]
надо подумать
