### ISSUE TITLE
[Suggest]Пачка предложений от Мурены

### ISSUE THREAD

**Issue by Murenaa** [FighterX2500/DMCAMarines#56]
1. Выпилить огнеупорность Равагеру
2. Уменьшить время такла у Крашера
3. Добавить возможность чинить танк
3.5 Пример, который дал вроде РуКэт, снимаешь модуль и например сваркой её чинишь до по-синения. Такая процедура будет выводить танк из игры на продолжительное время.

**Comment by Taushai** [comment]
4. научить маринов в кооперацию

**Comment by FighterX2500** [comment]
сер вы охуели
