### ISSUE TITLE
[Suggestion] Новые хитбоксы маринам

### ISSUE THREAD

**Issue by AdrianShepard** [FighterX2500/DMCAMarines#57]
На данный момент у нас хитбоксы работают так:
![unknown 1](https://user-images.githubusercontent.com/43182805/45377289-d5ebf280-b602-11e8-9f63-b506e0230ff8.png)

Я предлагаю изменить их чтобы они работали вот так:
![unknown](https://user-images.githubusercontent.com/43182805/45377331-f0be6700-b602-11e8-8c53-5d6834cf2906.png)

Данное нововведение поможет раз и навсегда избавится от тупых моментов за чужих когда Люркер или Раннер напрыгнули на марина и пытаются найти пиксель чтобы нанести удар или когда они на коротком расстоянии от Марина,но не могут попасть по спрайту,всё таки чужие идеальные охотники,а не криворукие рептилоиды которые не могут попасть по человеку который в пару сантиметрах от них. 
Таким же самым образом работают хитбоксы на Space Station : Corporate Mercenary.

**Comment by alexix1989** [comment]
А ты почему не думаешь о последствиях? Если два человека на тайле, а тебе нужно пулльнуть того, хитбокс которого не просвечивается, как ты это сделаешь? Хоткеи в этот раз не помогут, ибо хитбокс не поможет, остаётся только правый клик. Хуйня, короче.

**Comment by AdrianShepard** [comment]
@alexix1989 Тип один чел лежит а другой на нём? Ну во первых навести на спрайт чела который лежит я это ясно обозначил на примере и это возможно написать в коде разделив именно хитбокс человека на 2 части.1 часть будет приоритетнее из за чего если на неё навести удар по ней всегда будет проходить а 2 часть ту которую я дорисовал менее приоритетнее чем 1

**Comment by FighterX2500** [comment]
Идея очень плохая, промах это смысл ксеноморфов.

**Comment by AdrianShepard** [comment]
@FighterX2500 Промах уже есть в коде а я говорю про человеческую ошибку в миссклике
