### ISSUE TITLE
[Suggestion] У хаггера будет меньше стан если его кинет кэрри.

### ISSUE THREAD

**Issue by AdrianShepard** [FighterX2500/DMCAMarines#58]
В оригинале у хаггера стан 30 секунд из за чего кидать хаггеров бесполезно.
var/hugger_delay = 300
Строка выше по моему  отвечает за стан хаггера при его дропе\кидке.
Можно сделать исключительно дря кэрри,что стан хуггера будет изначально 25 секунд если кинул хаггера ИМЕННО Кэрри и стан будет у хаггера будет уменьшатся с возростом Кэрри.
Young=25 sec
Mature=20 sec
Elite=15 sec 
Ancient=10 sec
Это значит что если кэрри доживёт до Эншента то стан хуггеров если кинет он будет равен 10 секундам.Из за этого пуш на ФОБ с участием квины может быть легче для чужих если у них есть кэрри.Конечно же есть и альтернатива сделать так
Young=30 sec
Mature=25 sec
Elite=20 sec
Ancient=15 sec
Таким образом 15 секунд так как действие от скрича проходит через 8-10 секунд,но мне лично нравится вариант выше.
На данный момент функция кидать хуггеров бесполезна в большенстве случаях

**Comment by carrotman2013** [comment]
неактуально
