### ISSUE TITLE
[Suggestion] Cделать так чтобы марин не видел что творится у него за спиной

### ISSUE THREAD

**Issue by AdrianShepard** [FighterX2500/DMCAMarines#61]
![db7](https://user-images.githubusercontent.com/43182805/45448163-5893b100-b6da-11e8-9f04-f26acd7ec5e1.jpg)

**Comment by MoXuT0** [comment]
Это называется FOW aka field of view.

**Comment by AdrianShepard** [comment]
@MoXuT0 благодарю

**Comment by JeserTheFox** [comment]
Мечтал об этом еще со времен Сулако, но тогда нужно завозить аленям видимость всех хуманов как статики вне прямой видимости, чтобы сбалансировать.
