### ISSUE TITLE
[suggestion] Сделать свет как на Bay Station

### ISSUE THREAD

**Issue by AdrianShepard** [FighterX2500/DMCAMarines#62]
![image](https://user-images.githubusercontent.com/43182805/45448320-b88a5780-b6da-11e8-8a2c-dc9ad7491d15.png)
это так как у нас на данный момент работает свет

![image](https://user-images.githubusercontent.com/43182805/45448379-dce63400-b6da-11e8-97ce-1b788fae894a.png)
то что я предлагаю,новый свет так же понизит просвет сквозь стены на минимум и очень хорошо подходит под атмосферу

**Comment by StarRuCat** [comment]
Свет-то гуновский, бей его просто скоммуниздили.
