### ISSUE TITLE
Совсем немного справедливости и баланса предам

### ISSUE THREAD

**Issue by Rampoch** [FighterX2500/DMCAMarines#63]
https://github.com/FighterX2500/DMCAMarines/blob/fcbb06c73d336df13342beecc7ff85586721a337/code/modules/cm_preds/yaut_items.dm

908 линия	attack_speed = 18 //Will have the same speed as the glaive if there are two. 
изменить на:	attack_speed = 12 //Will have the same speed as the glaive if there are two.
Ибо наебка, у глевы значение меньше.

928 линия	if(prob(35) && !target.lying)
изменить на:	if(prob(45) && !target.lying)
Ибо плеть и так хуйня в сравнении с мечом, а так, с бафнутыми скимитарами и браслетом появится стимул пользоваться и другим разнообразным оружием тоже.

Было еще несколько моментов, но я уже забыл о них. Потом может допишу.

**Comment by FighterX2500** [comment]
Сделал
