### ISSUE TITLE
[Bug] Венты у варриора и дефендера

### ISSUE THREAD

**Issue by MoXuT0** [FighterX2500/DMCAMarines#64]
Все еще можно ползать по вентам за варриора или дефендера через верб Crawl through vent.
![rjomba](https://user-images.githubusercontent.com/34478337/45563472-1db68800-b856-11e8-865b-3ccaf1ec7e1d.png)

**Comment by carrotman2013** [comment]
не ебу, казалось что полено фиксил, проверю
