### ISSUE TITLE
кд на скрич с 60 до 300 сек

### ISSUE THREAD

**Issue by Leviathan21** [FighterX2500/DMCAMarines#67]
ShepardСегодня в 06:47
@Marcus Lawrence Нет,  ну ты сам видел это говна
Выбегает один еблан
Жмет кнопочку
Все, победил
-
для начала, скрич по эффекту самый натуральный "пресс х ту вин", специально когда все пиздец и надо что-то делать, низкий кд позволяет им стабильно набегать, а даже если и в ответ запушат, то кд уже обнулиться на следующий

**Comment by Leviathan21** [comment]
для сравнения раньше если квину могли на полпути с подствольника сбить, то сейчас ничем не остановишь ыыы)

**Comment by StarRuCat** [comment]
Слушай, тогда квине просто не будет смысла выходить из улья. Да и ксеноморфы лишатся возможности штурмовать укрепления, раунды будут просто затягиваться. Оглушение от крика не настолько уж большое, чтобы так сильно увеличивать откат
