### ISSUE TITLE
[Suggest] Танко-переезжание (Барсик, осталось чуть-чуть доделать, соберись)

### ISSUE THREAD

**Issue by JeserTheFox** [FighterX2500/DMCAMarines#69]
Танк все еще не переезжает микроволновки, мусорки, все виды ящиков, походу, ГРЕБАННОЕ ВЕДРО ИЗ-ПОД ШВАБРЫ, треноги пулемета (должно не уничтожаться, а либо толкаться в сторону, либо выпадать в свернутом виде), треноги сентряка (толкаться должно в сторону), мортиру (должно выпадать в переносимом виде, возможно, шоукейс. Сентряк должен кнокаться при переезде.

**Comment by AdrianShepard** [comment]
Сам предложил,сам сделал-вот это я уважаю!
