### ISSUE TITLE
[SUGG] оперирование на планете

### ISSUE THREAD

**Issue by Mo3goed** [FighterX2500/DMCAMarines#71]
В общем, чтобы не отправлять мариков на Алмаер при переломах, добавить Отрядным Медикам операционные наборы в кармашки, и сделать оперирование на складных кроватях.

Оперировать только переломы, возможно внутреннее кровотечение если не слишком имбово.

**Comment by RandomColonist** [comment]
Складные кровати - каталки. Инструменты можно засунуть в обычную выпотрошенную аптечку. Всё, иди, ебать, оперируй.

**Comment by Mo3goed** [comment]
Воровать инструменты из хирургии не есть хорошо

**Comment by RandomColonist** [comment]
А никто и не говорит про воровство, лол. Голосуй за разнерф скиллов, чтоб медики могли делать операции с делеем по скиллу, проси инструменты, 80% из которых не используются банально по количеству онлайна и оперируй сколько влезет.

**Comment by alexix1989** [comment]
Уже было на маринах, в итоге доктора на Алмаере были почти без работы.
