### ISSUE TITLE
[Suggest] Анти-танк баланс на Prison Station

### ISSUE THREAD

**Issue by JeserTheFox** [FighterX2500/DMCAMarines#73]
![firefox_2018-09-19_20-22-11](https://user-images.githubusercontent.com/43144601/45770043-fb53ae80-bc49-11e8-9e94-af47e8b319a2.png)
Вот в этом месте необходимы неразрушимые стены, сужающие проход до 2 тайликов. Таким образом танк все еще сможет пропушить аленей почти до хайва, но в сам Хайв марикам придется топать самим, как и на других картах.

**Comment by AdrianShepard** [comment]
Вообще я думаю можно поинтереснее сделать,каждая мапа разделена на 3 лайна если можно так сказать,можно миддл закрыть или перекрыть как-то либо сделать какие-то условия.Танк может продвинутся только через миддл.Например мидл открывается через 20-30 минут после посадки,можно так сделать
