### ISSUE TITLE
[1/3] Ребаланс [Морпехов] под реалии текущего медианного онлайна.

### ISSUE THREAD

**Issue by MrShepard** [FighterX2500/DMCAMarines#74]
Основная часть предложений относится к выпилу бесполезного и откровенно в текущих реалиях персонала Алмаера, без которого он однако не может функционировать. Если для кого-то сидеть доктором на Алмаере и фан, то например Реквизиция в её текущем состоянии - абсолютный ноуфан. Предложения носят комплексный характер, просьба не бежать с горящей жопой, если тебе не понравился какой-то отдельный пункт.

- Первое и главное - увеличение количества синтов с одного до двух. Были раунды, в котором был один дополнительно нащитспавленый синт. Абсолютно необходимое решение для наших реалий.

- Двигатели в текущем их состоянии - к хуям. Сразу оговорюсь, если у Барсика есть готовое предложение по этому делу - энджой. Корабль питают инфинити смесы, ломающиеся при столкновении с дропшипом.
 Соответственно выпил МТ и СЕ как профессию, и инженерного как части карты. 
UPD: На текущий момент с Барсиком порешили, что он хочет сложный двигатель и пакманы, которые включаются одним нажатием и энергии от которых хватает на полный средний раунд. Обещанного три года ждут. Я просто надеюсь ему хватит ума порезать инженерку до нормальных размеров.
 
- СД перенести на палубу с парковкой танка, что логично. СД на корме командной палубы военного корабля - уебанство. Будет справа от парковки.  Бриг слева от парковки техники. Следовательно на первом этаже CIC, Ангар,  Медбей, Брифинг, Реквизиция, Препы, Крио. На втором Бриг, парковка танка, СД. По моему мнению - идеальная компановка карты. Всегда открыт для предложений.
 
- Второй этаж медбея - нахуй, он бесполезен. Выпил.  Прикатите свои ксенохирургии и РнД в рабочем состоянии - место для этог всегда найдется. Выпил медикал ресерчеров, обычных докторов. Второй автодок. СМО и синты в любом случае остануться необходимы для первичной стабилизации пациентов и вырезания ксеноморфов (для кричащих о каэсике и казуализации - автодоки не могут в аборты).
 
- Реквизиция. Обязанности ИО совместить с обязанностями РО. Переписать ру-вики под это. Оставить ему одного грузчика, который будет совмещать обязанности МТ и его доступ совместно с карговским. Абсолютно все, кто играл при мне на РО жаловались на тотальную скуку. С другой стороны, ИО не берет абсолютно никто. Так убиваем двух зайцев. Не вижу ничего особенного, что первый заместитель капитана является одновременно заведующим по хозчасти.
 
- По боевым маринам - без изменений. Разве что добавить в вендоры Реквизиции обоймы с эксперементальными смарт-пулями и функцией ИФФ. По 3 на каждый стандартный  ствол в карго(3 обоймы на весь батальон, думаю нормально), окромя дробовика.

**Если наберу достаточно поддержки, отредактирую и перенесу в Гит-проджекты.**

**Comment by JeserTheFox** [comment]
Мы тут наоборот пытаемся избавить от уродского подвала.
Убирать что-то, чтобы потом возвращать - довольно идиотская затея, проще тупо не трогать, так как оно никому не мешает.
Как не мешают никому ресерчеры.

И главное - мы пытаемся увеличить онлайн, а все эти меры направлены на урезание слотов для ролек. Что не есть хорошо, имхо. Единственное, с чем я полностью согласен - движок на данный момент - говно редкостное. Идея с синтами вполне может спокойно заменить остальные изменения до увеличения онлайна.

**Comment by carrotman2013** [comment]
не читал
