### ISSUE TITLE
[2/3] Ребаланс [Алиенов] под реалии текущего медианного онлайна.

### ISSUE THREAD

**Issue by MrShepard** [FighterX2500/DMCAMarines#75]
С алиенами дела обстоят проще. Обычные алиены даже не нуждаются в нерфах. Однако, проовервотчив несколько раундов за отрядами, я понял основную проблему Барсикоморпехов - Квина и Танк. Но их слишком сильная взаимосвязь не позволяет занерфить что-то одно, иначе баланс сразу сломается.

Оба этих юнита раковы по своей сути и могут в правильных руках быть применены как тотальное оружие, выпиливающее противника без шансов. Однако, Квина является наверно единственным гарантированным юнитом, способным забрать танк на котором сидят не-раки и является единственной защитой от ксен от этогов ебучего чудовища. С другой стороны Квина имеет раковещую абилку - Скрич, который сейчас выглядит как кнопочка пресс икс ту вин. И тут я вижу несколь решений этой проблемы

1. Обоюдный выпил Скрича и Танка. Квина отлично может в самооборону с её таклами обычных морпехов на 15 секунд и сильнейшей кислотой. Она не должна играть в фронтового бойца 24/7 в принципе, СМ задумывали её абилки как помощь ксенам в случае жесткого штурма гнезда или наоборот, для выпила засевших на ФОБе морпехов, но уж точно не для бегания по фронту 24/7. С другой же стороны морпехи спокойно могут побеждать и без танка, однако в условиях х2 роста ксен и как следствия квины на фронтлайне 24/7 победа без танка становится проблематичной.
В конце концов, выпилить танк мне не дадут танкокультисты, даже взамен на обоюдный выпил скрича.

2. Квина может использовать Скрич только определенное время после выхода с овера. Такой подход, во-первых, избавит от фронтлайн квин, скричащих каждую минуту, во-вторых заставит ксен организовывать свой ФОБ для атаки на ФОБ маринов. Тактикул! КД на посадку овер снизить с **300 секунд до 180**, возможность Скричить с таким же **КД 60 секунд** после выхода с гнезда на протяжении **200 секунд**. Ну и взамен нерф танка, невозможность ставить одновременно ОД и миниган. Этот вариант мне нравится больше.

- Сделать х2 рост, да хоть х3, но только первые 30 минут с начала раунда. До Барсяна не доходит, что три элит квины в одном раунде - не комильфо, ксены тупо закидывают морпехов элитным мясом.

С алиенами на этом пожалуй все.

**Comment by carrotman2013** [comment]
бляяяяяять! !!! пиздос!!! сука ты уеб ок блять ебаный тебя что ЕБЕТ ЭТО ЧТОЛИ сука БЛЯТЬ вот за ТАКИЕ вопросы у меня в улье убивают нахер! ЭЭШ!
