### ISSUE TITLE
[3/3] Ребаланс [Карт] под реалии текущего медианного онлайна.

### ISSUE THREAD

**Issue by MrShepard** [FighterX2500/DMCAMarines#76]
Пара соображений по картам.

- ЛВ-624. Добавить телекоммы под гидропоникой заместо фитнеса. Хуйня какая-то, на каждой карте телекомы есть, на ЛВ нет.

- Призонка. Убрать телекомы с юга ЛЗ1. Поставить их над тем местом, где марины ставят ФОБ. С юга убрать дверные проемы, поставить стенку, проплавляемую только кислотой квины и бойлера. Логичное решение, мы одновременно дадим больше безопасности морпехам, но не ограничим ксен в возможности пуша. Будет как на Бигреде, отличное решение. 

- Бигред. Тут все отлично, хорошая карта.

- Айс. Тотальная параша, нужно ждать полного перепила от ТГшников.

**Comment by JeserTheFox** [comment]
Не нравится идея насчет добавления коммов на ЛМ. Это единственная карта, где у тебя 100% будут коммы независимо от уровня ебланства инженеров. В этом один из ее немногочисленных плюсов.

**Comment by carrotman2013** [comment]
даже говорить ничего не буду, уже впилено
