### ISSUE TITLE
[Suggest] Объдинить MT и CT в Crew Member(Ship Crew)

### ISSUE THREAD

**Issue by JeserTheFox** [FighterX2500/DMCAMarines#77]
Объединить роли MT и CT в новую универсальную роль. Тоже с RO и CE. Таким образом у нас останутся отделы MP, Медбея, Командование и Отдел обеспечения и технической поддержки. Ну и марики, куда же без них.

**Comment by Fray2** [comment]
Вот это пожалуй и надо сделать. МТ юзелесс потому что корабль никогда не ломается, а у CT только одна задача.
К тому же дать новой рольке доступы в карго/инженерку/ОБ и соответсвующие скиллы. @carrotman2013

**Comment by carrotman2013** [comment]
Закрывай.
