### ISSUE TITLE
[Suggest] Нерф такла крашера

### ISSUE THREAD

**Issue by JeserTheFox** [FighterX2500/DMCAMarines#84]
На данный момент такл крашера такой же как у дрона: высокий шанс, длительность около 7-10 реальных секунд. Надо уменьшать длительность как минимум, в идеале шанс тоже немного снизить.

**Comment by AdrianShepard** [comment]
Лучше наоборот уменьшить такл дрону чем крашеру

**Comment by JeserTheFox** [comment]
Такл дрону нужен для работы с захваченными, а вот крашер не должен учавствовать в ближнем бою особо, у него роль другая. Либо сделать, чтобы крашер вместо такла отталкивал, я не знаю. Но такл на 7-10 секунд, это пиздец.

**Comment by JeserTheFox** [comment]
Марин не быстрее крашера когда крашер абузит антибодиблок систему.

**Comment by carrotman2013** [comment]
нет не надо.
