### ISSUE TITLE
Добавить Специалиста по CQC (close quarter combat) 

### ISSUE THREAD

**Issue by AdrianShepard** [FighterX2500/DMCAMarines#92]
Новый вид специалиста его основное отличие в том,что он не может пользоваться обычным оружием дальнего боя.Одет он в Экспериментальную Броню Хамелеон от WU и экипирован  специальным ножом и боевой катаной,а так же специальным пистолетом который сделан специально для его костюма. Дело в том что его экипировка   работает хорошо только с его костюмом (а значит держа специльный пистолет или катану он может с ними входить в невидимость с обычной экипировкой марина он  не войдет в невидимость из за того что обычная экипировка будет летать в воздухе). 

По Лору костюм сделан из украденных технологий Хищника.Специалиста обучили обезвреживать цели которые хорошо вооружены и работать в одиночку.Как правильно бороться с врагом на ближней дистанции.Годны тренировок .Специалист был создан чтобы безопасно обезвреживать врагов (CLF,UPP) без наведения шума
https://youtu.be/TjGtkX3nazY?t=139

В его наборе будут следующие предметы.

- Броня Хамелеон (Который может автоматически вводить в специалиста обезболивающее и лечащие вещества и имеет более улучшенный режим невидимости,а так же в которой встроен механизм самоуничтожения о котором даже спек не знает)

- Шлем хамелеон

- Тактические боевые ботинки хамелеон

- Тактический боевой нож который входит в тактические ботинки

- Close combat Katana

- Экспериментальный пистолет уже со встроенным улучшенным глушителем (который нельзя снять) может использовать патроны которые есть у скаута в обойме (high velocity bullets)

- Подобие метательного диска Хищника,наносит меньше урона но летает быстрее.

- Cверх звуковая граната (в неком радиусе станит всё живое,включая ксеноморфоф)

Годы хороших тренеровок и Броня Хамелеон сделает из Специалиста смертельного бойца одиночку ближнего боя.Который может входить в невидемость и из засады уничтожать врага.

- В качестве гемплея- это Спек-Одиночка,который опирается только на ближний бой,этого проворного ублюдка тяжело сбить с ног так как он будет очень часто уворачиваться,а даже если ксеноморфу получится сбить его с ног таклом то он встанет на ноги очень быстро.Его броня блокирует большинство кислот,а значит даже нейротоксином не факт что получится его сбить.Остаётся только убить ублюдка слешэм в честном бою.Спек по идее должен проводить большинство времени невидемым в поисках одиночных целях после чего наказывать их своей катаной по горлу.
Хищник же знает,что у спека спиженные технологии их народа из за чего этот специалист является очень достойной добычей.
![image](https://user-images.githubusercontent.com/43182805/45928997-766fda00-bf54-11e8-8cbd-191128c00806.png)
![image](https://user-images.githubusercontent.com/43182805/45929001-8c7d9a80-bf54-11e8-9335-274e1e778ba1.png)

**Comment by RandomColonist** [comment]
Еле-еле осилил до конца. Влажные и больные маняфантазии уберспециалиста-предоёба. Специалист с ГОДАМИ (кто успел взять набор - тому +5 годиков к возрасту сразу) который бьётся в одиночку, имеет уберброню с суперпоказателями, инвизом и медикаментами (копия предоброни с предофичами), целый АРСЕНАЛ всякого уберговна (кнокающий пистолет под винтовочные патроны, уберкатана и какой-то крутой нож вкупе с МЕТАТЕЛЬНЫМ ДИСКОМ ПРЕДА БЛЯТЬ) и даже СТАНЯЩАЯ КСЕНОМОРФОВ ГРАНАТА КОТОРОЙ НЕТ ДАЖЕ У ПРЕДОВ, ОГА. Ты даже НЕ СКРЫВАЕШЬ СНОУФЛЕЙКОВОСТИ ЭТОГО ГОВНА, ПРЯМЫМ ТЕКСТОМ ГОВОРЯ, ЧТО ЭТО МАРИНСКАЯ КОПИЯ ПРЕДАТОРА. Пиздец, ты этот кусок говна на серьёзном ебале высрал или как пример хуёвого саджестшена? Больше похоже на второе. Если нет - желаю таким манядевелоперам спидорака почек.


![image](https://user-images.githubusercontent.com/17860944/46405228-407ae480-c710-11e8-8fee-8f6babd301ae.png)

**Comment by bob467** [comment]
Это уже бред полный.

**Comment by carrotman2013** [comment]
блять нет
